import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 按导航栏板块拆分侧边栏，使每个顶部导航项只在自己板块的页面里高亮，
  // 避免四个 type:doc 导航项共用同一侧边栏时一起被判定为 active。
  quickStartSidebar: ['intro'],
  apiSidebar: [{type: 'autogenerated', dirName: 'packs'}],
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
  extraLibSidebar: [{type: 'autogenerated', dirName: 'extra_lib'}],
};

export default sidebars;
