/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

    tutorialCommands: [ { type: 'autogenerated', dirName: 'tutorials/a1_commands' } ],
    tutorialAddons: [ { type: 'autogenerated', dirName: 'tutorials/a2_addons' } ],
    tutorialScripts: [ { type: 'autogenerated', dirName: 'tutorials/a3_scripts' } ],

    docCommands: [ { type: 'autogenerated', dirName: 'docs/commands' } ],
    docAddons: [ { type: 'autogenerated', dirName: 'docs/addons' } ],
    docItems: [ { type: 'autogenerated', dirName: 'docs/items' } ],
    docBlocks: [ { type: 'autogenerated', dirName: 'docs/blocks' } ],
    docScripts: [ { type: 'autogenerated', dirName: 'docs/scripts' } ],

    devTemplate: [ { type: "autogenerated", dirName: 'dev_template' } ],

};

export default sidebars;
